name: Update NPM Dependencies
description: Checks if there are updates to NPM packages, and creates a PR with the updated package*.json files

# inputs:
#   base-branch:
#     description:
#     default:
#     required: 
#   head-branch:
#     description:
#     default:
#     required: 
#   working-directory:
#     description:
#     required:
#   gh-token:
#     description:
#     required:
#   debug:
#     description:
#     default:

# outputs:
#   updates-available:
#     description:

runs:
  using: node20
  main: index.js